name: 'Get Vercel URL'
description: 'Get the Vercel URL from a build'
inputs:
  vercel-token:
    description: 'Vercel token'
    required: true
  vercel-org-id:
    description: 'Vercel org id'
    required: true
  vercel-project-id:
    description: 'Vercel project id'
    required: true
  github-branch:
    description: 'Github branch'
    required: true
  github-commit:
    description: 'Github commit commit'
    required: true
  start-timeout:
    description: 'How long to wait to see deployment starting'
    default: 600
  finish-timeout:
    description: 'How long to wait to see deployment finish'
    default: 600
  pagination-limit:
    description: 'How many pages to search for the deployment'
    default: 2
  wait:
    description: 'Should it wait until the deployment is ready'
    default: true
outputs:
  deployment-url:
    description: 'Deployment URL'
runs:
  using: 'node16'
  main: 'dist/index.js'
